title: A52/A72 guide
description: Various ROM and Recovery installation guides for Samsung A52 4G/A72
theme: just-the-docs

url: https://guide.simon1511.de

color_scheme: sm7125

footer_content: "Copyright &copy; 2024 Simon1511 and Risen. All rights reserved."

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow